apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: go-metrics-app
  namespace: go-metrics-app
spec:
  selector:
    matchLabels:
      app: go-metrics-app
  namespaceSelector:
    matchNames:
      - go-metrics-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
