apiVersion: v1
kind: Service
metadata:
  name: go-metrics-app
  namespace: go-metrics-app
  labels:
    app: go-metrics-app
spec:
  selector:
    app: go-metrics-app
  ports:
    - name: http
      port: 80
      targetPort: http
